- name: RKE2 Deployment
  hosts: master[0]
  become: yes
  vars_files:
    - vars.yml
  roles:
    - rke2_initial

- name: Configure and Start RKE2 on Worker Nodes
  hosts: master[1:]
  become: yes
  vars_files:
    - vars.yml
  roles:
    - rke2_server

- name: Configure and Start RKE2 on Worker Nodes
  hosts: worker
  become: yes
  vars_files:
    - vars.yml
  roles:
    - rke2_agent
