---
- name: Install RKE2
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -
  args:
    creates: /var/lib/rancher/rke2/bin/

- name: Ensure the RKE2 config directory exists
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Retrieve the RKE2 node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: node_token
  when: inventory_hostname == groups['master'][0]

- name: Set RKE2 token fact
  ansible.builtin.set_fact:
    rke2_token: "{{ node_token['content'] | b64decode }}"
  when: inventory_hostname == groups['master'][0]

- name: Create RKE2 config for master nodes
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: Start RKE2 server
  ansible.builtin.systemd:
    name: rke2-server
    enabled: yes
    state: started
